repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version of flake8
    hooks:
      - id: flake8
        args:
          - --max-line-length=79  # Optional: customize the line length if needed
